### ISSUE TITLE
upgrade-manager-v2: Metrics don't seem to have the correct values.

### ISSUE THREAD

**Issue by shreyas-badiger** [keikoproj/upgrade-manager#248]
I did an upgrade for around 100 odd nodes. The values are too small to be real. We need to investigate.

```
status:
  currentStatus: completed
  lastBatchNodes:
  - ip-10-232-53-73.us-west-2.compute.internal
  lastDrainTime: "2021-06-03T18:37:37Z"
  lastTerminationTime: "2021-06-03T18:37:37Z"
  startTime: "2021-06-02T16:51:04Z"
  statistics:
  - durationCount: 873
    durationSum: 3.262345917s
    stepName: kickoff
  - durationCount: 257
    durationSum: 1m44.965598877s
    stepName: desired_node_ready
  - durationCount: 216
    durationSum: 986.712183ms
    stepName: predrain_script
  - durationCount: 159
    durationSum: 1m8.860814182s
    stepName: drain
  - durationCount: 159
    durationSum: 190.862µs
    stepName: postdrain_script
  - durationCount: 159
    durationSum: 30.50975ms
    stepName: post_wait
  - durationCount: 200
    durationSum: 1m53.485146372s
    stepName: terminate
  - durationCount: 200
    durationSum: 350.432µs
    stepName: post_terminate
  - durationCount: 200
    durationSum: 4m48.567501589s
    stepName: total
  totalNodes: 107
```
